version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu
hooks:
  BeforeInstall:
    - location: Scripts/UnzipResourceBundle.sh
  ApplicationStart:
    - location: Scripts/RunFunctionalTests.sh
      timeout: 3600