version: 0.0
os: linux
files:
  - source: /app.py
    destination: /home/ubuntu
hooks:
  AfterInstall:
    - location: Scripts/UnzipResourceBundle.sh
  ApplicationStart:
    - location: Scripts/RunFunctionalTests.sh
      timeout: 3600